### PR TITLE
move minimatch dep from dev to prod deps

### PR DESCRIPTION
**Pull request by andykais**
The dependency `minimatch` is marked as a dev dependency when it is used in the package source here: https://github.com/sysgears/mochapack/blob/master/src/runner/TestRunner.js#L6

This was causing the mochapack to not work when installed via `pnpm`.

### CODE REVIEW

**Comment by vlasenko** [comment]
Looks good, thank you @andykais!

**Comment by andykais** [comment]
no prob!

**Comment by vlasenko** [comment]
@andykais Published `mochapack@1.1.4` with your fix

**Comment by andykais** [comment]
just tested it and the fix works! 🎉 Thanks guys! Now I just need to track down all the other projects giving me trouble with pnpm 🔍

**Pull request merged**
