### PR TITLE
Upgrade to Typescript

### PR DESCRIPTION
**Pull request by Jack-Barry**
**What's the problem this PR addresses?**

Removes Flow and switches the repo over to TypeScript, as per discussion in #17 

**How did you fix it?**

1. Used [`flow-to-ts`](https://github.com/Khan/flow-to-ts) to convert all `src` files
2. Used `flow-to-ts` to convert applicable `test` files
3. Fixed type errors or threw in a `// @ts-ignore` where it wasn't worth the battle for now
4. Ensured tests were still passing with some minor adjustments
5. Ensured coverage reporting is functioning properly
6. Updated tooling scripts to use TypeScript

Some of these commits overlap with #49 PR but I'm keeping this one separate for tracking purposes since it's a different issue being addressed more massive overhaul of the tooling. The other PR is ready to go and has passed all tests whereas this one needs to be vetted via CI tooling and probably requires further review.

### CODE REVIEW

**Comment by larixer** [comment]
@Jack-Barry Could you merge with updated upstream master please?

**Comment by Jack-Barry** [comment]
One thing to note here is that the code coverage percentage currently reported (95%) will drop significantly. 

Given the brittle nature of some of the tests this doesn't surprise me, I am inclined to believe the new value reported is more accurate. If there's something I missed in updating the coverage reporting in the shift over to TS just let me know, thanks!

**Comment by larixer** [comment]
@Jack-Barry Good stuff, many thanks!

**Comment by JamesMcMahon** [comment]
Thanks for biting this one off.

**Comment by Jack-Barry** [comment]
## Before
BeforeTS

## After

AfterTS

Ahhh, that's better 😊

**Comment by larixer** [comment]
@Jack-Barry I fully agree! :)

**Pull request merged**
