### PR TITLE
Check in npm package-lock.json

### PR DESCRIPTION
**Pull request by JamesMcMahon**
**What's the problem this PR addresses?**

Checks in a `package-lock.json` file. This is suggested by the [npm people as a best practice](https://github.com/npm/cli/blob/752652e1f8be40992baa1da6d5cb850dcbd89344/doc/files/package-lock.json.md).

Excerpt:

> This file is intended to be committed into source repositories, and serves
various purposes:
> * Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> * Provide a facility for users to "time-travel" to previous states of `node_modules` without having to commit the directory itself.
> * To facilitate greater visibility of tree changes through readable source control diffs.
> * And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

**How did you fix it?**

Generated the file automatically while working on another PR.

### CODE REVIEW

**Comment by JamesMcMahon** [comment]
This will also facilitate fixing the numerous issues found by running `npm audit`.

**Comment by vlasenko** [comment]
@JamesMcMahon This project uses `yarn` currently and `yarn.lock` has been committed already. Committing both lock files is not a good idea, because there must be only one source of truth about dependency tree and we would have two sources of truth.

**Comment by JamesMcMahon** [comment]
Ah jeez, I totally missed that. Make sense that you wouldn't want a `package-lock.json` 😁

Follow up PR https://github.com/sysgears/mochapack/pull/32. To update the docs to make it clearer you are using Yarn.

**Comment by vlasenko** [comment]
@JamesMcMahon Thank you for your pull requests. I will be able to review them tomorrow. Meanwhile I have given you write perms to this repository, so you can create branches for your future PRs directly on this repo.

**Pull request closed without merging**
