### PR TITLE
Fix --file not being respected

### LINKED ISSUE #20: Add support for --file option
> #### [`--file <file/directory/glob>`](https://mochajs.org/#-file-filedirectoryglob)
> Explicitly include a test file to be loaded before other test files files. Multiple uses of --file are allowed, and will be loaded in order given.
> 
> Useful if you want to declare, for example, hooks to be run before every test across all other test files.
> 
> Files specified this way are not affected by --sort or --recursive.
> 
> Files specified in this way should contain one or more suites, tests or hooks. If this is not the case, consider --require instead.

### PR DESCRIPTION
**Pull request by willsoto**
**What's the problem this PR addresses?**

`--file` not being respected

**How did you fix it?**

Any files that were added via --file were being blown away when Webpack's entrypoints were being added.
In order to resolve this, the entrypoints now get added via Mocha's addFile method.

Closes #20

### CODE REVIEW

**Comment by larixer** [comment]
@willsoto Nice, many thanks!

**Comment by larixer** [comment]
Published in `mochapack@2.0.4`

**Comment by willsoto** [comment]
Thanks for the quick review and release!

**Comment by willsoto** [comment]
@larixer It doesn't seem like the change made it into `2.0.4`. I just upgraded but the compiled code does not contain the change I made.

Screen Shot 2020-10-16 at 9 58 10 AM
Screen Shot 2020-10-16 at 9 58 15 AM

**Comment by larixer** [comment]
@willsoto Could you check if it came through into `2.0.5` ?

**Comment by willsoto** [comment]
@larixer - works now. Thank you very much!

**Comment by larixer** [comment]
@willsoto Thank you!

**Pull request merged**
