### PR TITLE
Migrate away from deprecated function calls

### PR DESCRIPTION
**Pull request by jayaddison**
**What's the problem this PR addresses?**
Fixes https://github.com/sysgears/mochapack/issues/53
Depends on https://github.com/sysgears/mochapack/pull/58

**How did you fix it?**
- Instead of calling the deprecated functions, provide their arguments as options to the `Mocha` constructor
- Update the test coverage of the options accordingly

### CODE REVIEW

**Comment by jayaddison** [comment]
Ideally best to see if we can merge https://github.com/sysgears/mochapack/pull/60 into `master` first, then merge those changes back here to ensure that this works correctly for `mocha` v7.

**Comment by larixer** [comment]
@jayaddison Yep, just merged it

**Comment by larixer** [comment]
@jayaddison Looks like tests pass, LGTM, thank you!

**Comment by jayaddison** [comment]
Brilliant, thanks @larixer!

Do you know whether there are any upcoming releases planned for `mochapack`?  (I'd like to upgrade to reduce some deprecation warning noise; but it's not urgent)

**Comment by larixer** [comment]
@jayaddison Yep, I can craft a release for you, no problems. Give me few mins

**Comment by larixer** [comment]
@jayaddison Published `mochapack@1.1.14`

**Comment by jayaddison** [comment]
@larixer Awesome, thank you!

**Pull request merged**
