### PR TITLE
Upgrade Flow and Babel dependencies

### PR DESCRIPTION
**Pull request by Jack-Barry**
**What's the problem this PR addresses?**

I forget where I saw it, but remember reading that a shift over to TypeScript from Flow would be welcome here. I decided to go ahead and upgrade Babel so that the transition will be more feasible.

* This fixes at least part of #47 by upgrading Babel dependencies
* This upgrades the Flow dependency so that plugin for VS Code can be used until the shift over to TypeScript is complete

**How did you fix it?**

Upgraded dependencies and fixed any places that the upgrades broke tests.

### CODE REVIEW

**Comment by Jack-Barry** [comment]
Taking another look at this on a PC at work - everything was passing on my Mac at home.

**Comment by Jack-Barry** [comment]
Attempting a change in the text fixture - passes on my WSL under `10.17.0`, but the erroring test is skipped on Windows OS.

**Comment by Klitsenko** [comment]
@Jack-Barry These `cli --watch` tests are unreliable (they fail for me all the time since I forked mocha-webpack), I'm not sure why are there indeed. I'm fine with disabling them for now. If you are brave you can figure out how to make them more reliable.

**Comment by Jack-Barry** [comment]
I'm brave but not feeling that brave right now 😐 haha. Reworked the file to use `xdescribe` instead of commenting out specs so that at least the tests are visible as skipped when being run.

**Comment by Klitsenko** [comment]
@Jack-Barry Very nice, thank you!

**Comment by larixer** [comment]
Cool, looks great, many thanks!

**Pull request merged**
