### PR TITLE
Experiment: attempt to restore Travis CI

### PR DESCRIPTION
**Pull request by jayaddison**
**What's the problem this PR addresses?**
Continuous integration via Travis seems broken at the moment; see this [example build log](https://travis-ci.com/github/sysgears/mochapack/jobs/487456066#L243) from pull request #92.

The problem is potentially due to over-escaping of the [`before_script` commands](https://github.com/sysgears/mochapack/blob/0bd572be936a4347bc9c9c132a89141f05318c73/.travis.yml#L27-L29), based on the [observed output](https://travis-ci.com/github/sysgears/mochapack/jobs/487456066#L243):

```
The command "yarn add -D webpack@$WEBPACK_VERSION" failed and exited with 1 during .
```

Before opening and/or merging further changes it'd be good to get tests green again.

**How did you fix it?**
This isn't yet a confirmed fix; but the approach taken is to remove the outer double-quotes from the command specification.

### CODE REVIEW

**Comment by jayaddison** [comment]
Aha: the problem may was within one of the [nested build output steps](https://travis-ci.com/github/sysgears/mochapack/jobs/487541304#L236):

```
[noisy start-of-line removed] ... provides eslint@npm:6.8.0 with version 6.8.0 which doesn't satisfy ^4.9.0 requested by eslint-config-airbnb-base@npm:12.1.0
```

So updating and/or tuning a few of the `package.json` dependency references may resolve this.

**Comment by jayaddison** [comment]
NB: There are other dependency updates that could be beneficial to apply; the goal in this pull request is to get continuous integration working again first, and then dependency freshness can be applied as a subsequent set of changes.

**Comment by jayaddison** [comment]
Nope, it's been a long day.  The `eslint` messages are warnings, not errors.  The [error line](https://travis-ci.com/github/sysgears/mochapack/jobs/487564792) appears to be:

```
fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=127e8e: Cannot apply hunk #1 (set enableInlineHunks for details)
```

This has been resolved in another codebase by upgrading the Yarn version https://github.com/registreerocks/registree-core/pull/370 .  In the builds for this repository we are dependent on the underlying OS environment.

Can/should we upgrade the Yarn version within the CI container, either by selecting a more up-to-date environment, or by performing a runtime upgrade?

**Comment by jayaddison** [comment]
cc @larixer

**Comment by larixer** [comment]
Looks good to me, thank you!

**Pull request merged**
